# Generated by Django 4.2.1 on 2023-05-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('context', models.TextField(max_length=250)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
