# Generated by Django 4.2.1 on 2023-05-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Заняття', 'verbose_name_plural': 'Заняття'},
        ),
    ]
