# Generated by Django 4.2.1 on 2023-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
